@MovieBase.Api_HostAddress = https://localhost:7267
@user=admin
@password=P@$$w0rd1
@email=admin@notadomain.com

@token=CfDJ8JHE-tf9yUBDnwjMNhyy7TsvApyxgGD-y72xBs-oYTuDtirPfyTK33vi0ai7r-4BrprdHDuYTtJVz7-YuG4XWhtdhI16avWTMyy0OVeeuQDdzeVdPXA45netv59neF4wfLNGeP0i0mVctnRCWQU0eQxRGog2hGreWWA6T-r5u3bLAkn9V-J3rOLUsEWXrMW9tBaeWZx1jkD8TuLn8J_YnFaTG0dIj_OnmTpv80ph4cY7IsTytuZ0-fzODczZ9BFuwkPgt8KpE3ONeIEDuMQVwIdbQ0Zke2AVwSh6r0fKgb9rjQDAsChfP2tLRJGF96MDv7CXogyaO-BjiJygeviY8YbAma4PkQUPYtHiLBYKTfxDPHszkp_slUkafuVQr84_dSnmsoQJPqnjeubmYCZ17P8WYWrp9vFKgQp1rgPmogXOLX--ooe7O5hrm3PWW73NvSVewus_g6Wu4AZEMIi4njLbTtlhrFveTRq57WYHWVrluF8AQgGN3vtT-HHTJ9E0De0o-waE3ULSTsozAODKhnlABeb5ziyGGbGJsAC0owMtZgYgKJLXO32JKm4MaJ4hiUIAYgCJ6tFSyEpNJRxFbZasThyZyYH_hkhnNK-NpQQ7eF6_9AZ9b0rwri1TMLDt_uiDykQIUulBel4XlJC2mlGZgFN56nx2pvyqjXvDpK1P9CSUVSY7I6PckNmOLja6Wbt35zvEQnlHKsBPUXB07a4


POST {{MovieBase.Api_HostAddress}}/register
Content-Type: application/json

{
  "username": "{{user}}",
  "password": "{{password}}",
  "email": "{{email}}"
}

###

POST {{MovieBase.Api_HostAddress}}/login?useCookies=false
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

GET {{MovieBase.Api_HostAddress}}/movies/list/10/5
Accept: application/json

###

GET {{MovieBase.Api_HostAddress}}/movies/list
Accept: application/xml

###

GET {{MovieBase.Api_HostAddress}}/movies/1
Accept: application/json
Authorization: Bearer {{token}}

###


POST {{MovieBase.Api_HostAddress}}/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 0,
  "title": "Some movie",
  "director": "Nobody",
  "released": "1966-11-28"
}
###

POST {{MovieBase.Api_HostAddress}}/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "director": "Nobody",
  "released": "1966-11-28"
}
###

DELETE {{MovieBase.Api_HostAddress}}/movies/52
Accept: application/json

###

PUT {{MovieBase.Api_HostAddress}}/movies
Content-Type: application/json

{
  "id": 53,
  "title": "Updated Name",
  "director": "Nobody",
  "released": "1966-11-28"
}
###

PATCH {{MovieBase.Api_HostAddress}}/movies/1
Accept: */*
Content-Type: application/json-patch+json

[
  {
    "op": "add",
    "path": "/director",
    "value": "Ridley Scott"
  }
]

###

